/**
 * AUTO-GENERATED by scripts/generate-from-schema.js from schema.json.
 * DO NOT EDIT — re-run `node scripts/generate-from-schema.js`.
 */

/** Fields added by the orchestrator to every routed event. */
export type OrchestratorStamp = {
  ts?: number;
  _from?: string;
};

// ---- Audio ----

export type AudioChunkEvent = OrchestratorStamp & {
  type: "audio.chunk";
  channels: number;
  data: string;
  durationMs: number;
  format: string;
  sampleRate: number;
  trackId: string;
  kind?: "speech" | "sfx";
};

export type AudioLevelEvent = OrchestratorStamp & {
  type: "audio.level";
  dbfs: number;
  peak: number;
  rms: number;
  trackId: string;
};

// ---- Speech Recognition ----

export type SpeechPartialEvent = OrchestratorStamp & {
  type: "speech.partial";
  text: string;
  trackId: string;
};

export type SpeechDeltaEvent = OrchestratorStamp & {
  type: "speech.delta";
  text: string;
  trackId: string;
  replaces?: string;
};

export type SpeechFinalEvent = OrchestratorStamp & {
  type: "speech.final";
  text: string;
  trackId: string;
  confidence?: number;
};

export type SpeechPauseEvent = OrchestratorStamp & {
  type: "speech.pause";
  pendingText: string;
  silenceMs: number;
  trackId: string;
};

// ---- Agent/LLM ----

export type AgentSubmitEvent = OrchestratorStamp & {
  type: "agent.submit";
  requestId: string;
  text: string;
};

export type AgentDeltaEvent = OrchestratorStamp & {
  type: "agent.delta";
  delta: string;
  requestId: string;
  seq: number;
};

export type AgentCompleteEvent = OrchestratorStamp & {
  type: "agent.complete";
  requestId: string;
  text: string;
  tokenUsage?: { input: number; output: number };
};

export type AgentThinkingEvent = OrchestratorStamp & {
  type: "agent.thinking";
  requestId: string;
};

export type AgentToolStartEvent = OrchestratorStamp & {
  type: "agent.tool_start";
  requestId: string;
  toolCallId: string;
  title?: string;
};

export type AgentToolDoneEvent = OrchestratorStamp & {
  type: "agent.tool_done";
  requestId: string;
  status: string;
  toolCallId: string;
};

export type AgentHistoryEvent = OrchestratorStamp & {
  type: "agent.history";
  role: string;
  text: string;
  requestId?: string;
  toolCallId?: string;
};

// ---- Control ----

export type ControlInterruptEvent = OrchestratorStamp & {
  type: "control.interrupt";
  reason: string;
};

export type ControlStateEvent = OrchestratorStamp & {
  type: "control.state";
  component: string;
  state: string;
};

export type ControlErrorEvent = OrchestratorStamp & {
  type: "control.error";
  component: string;
  fatal: boolean;
  message: string;
};

// ---- Lifecycle ----

export type LifecycleReadyEvent = OrchestratorStamp & {
  type: "lifecycle.ready";
  component: string;
};

export type LifecycleDoneEvent = OrchestratorStamp & {
  type: "lifecycle.done";
  component: string;
};

// ---- Log ----

export type LogEvent = OrchestratorStamp & {
  type: "log";
  component: string;
  level: "info" | "warn" | "error" | "debug";
  message: string;
};

// ---- Player ----

export type PlayerStatusEvent = OrchestratorStamp & {
  type: "player.status";
  agentState: unknown;
  playing: unknown;
  sfxActive: boolean;
};

// ---- Node ----

export type NodeStatusEvent = OrchestratorStamp & {
  type: "node.status";
  text: string;
};

// ---- Union types ----

export type AudioEvent = AudioChunkEvent | AudioLevelEvent;

export type SpeechEvent =
  | SpeechPartialEvent
  | SpeechDeltaEvent
  | SpeechFinalEvent
  | SpeechPauseEvent;

export type AgentEvent =
  | AgentSubmitEvent
  | AgentDeltaEvent
  | AgentCompleteEvent
  | AgentThinkingEvent
  | AgentToolStartEvent
  | AgentToolDoneEvent
  | AgentHistoryEvent;

export type ControlEvent =
  | ControlInterruptEvent
  | ControlStateEvent
  | ControlErrorEvent;

export type LifecycleEvent = LifecycleReadyEvent | LifecycleDoneEvent;

export type LogEventType = LogEvent;

export type PlayerEvent = PlayerStatusEvent;

export type NodeEvent = NodeStatusEvent;

export type PipelineEvent =
  | AudioEvent
  | SpeechEvent
  | AgentEvent
  | ControlEvent
  | LifecycleEvent
  | LogEvent
  | PlayerEvent
  | NodeEvent;

/** An event with a `type` field that doesn't match a known type. Forwarded unchanged. */
export type UnknownEvent = OrchestratorStamp & {
  type: string;
  [key: string]: unknown;
};

export type AnyEvent = PipelineEvent | UnknownEvent;

// ---- Type discrimination ----

const KNOWN_TYPES = new Set([
  "audio.chunk",
  "audio.level",
  "speech.partial",
  "speech.delta",
  "speech.final",
  "speech.pause",
  "agent.submit",
  "agent.delta",
  "agent.complete",
  "agent.thinking",
  "agent.tool_start",
  "agent.tool_done",
  "agent.history",
  "control.interrupt",
  "control.state",
  "control.error",
  "lifecycle.ready",
  "lifecycle.done",
  "log",
  "player.status",
  "node.status",
]);

export function isKnownEventType(type: string): boolean {
  return KNOWN_TYPES.has(type);
}

// ---- Serialization ----

export function parseEvent(json: string): AnyEvent {
  const obj = JSON.parse(json);
  if (!obj || typeof obj !== "object" || typeof obj.type !== "string") {
    throw new Error("Invalid event: missing 'type' field");
  }
  return obj as AnyEvent;
}

export function serializeEvent(event: AnyEvent): string {
  return JSON.stringify(event);
}

// ---- Helpers ----

/** Create an event with the given type and payload. */
export function createEvent<T extends AnyEvent>(event: T): T {
  return event;
}

/** Stamp an event with orchestrator metadata. */
export function stampEvent<T extends AnyEvent>(
  event: T,
  from: string,
): T & Required<OrchestratorStamp> {
  return { ...event, ts: Date.now(), _from: from };
}
