/**
 * AUTO-GENERATED by acpfx-codegen from packages/schema (Rust).
 * DO NOT EDIT — re-run `cargo run -p acpfx-schema --bin acpfx-codegen`.
 */

import { z } from "zod";

export const OrchestratorStampSchema = z.object({
  ts: z.number().optional(),
  _from: z.string().optional(),
});

export const AudioChunkEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("audio.chunk"),
  trackId: z.string(),
  format: z.string(),
  sampleRate: z.number(),
  channels: z.number(),
  data: z.string(),
  durationMs: z.number(),
  kind: z.enum(["speech", "sfx"]).optional(),
});

export const AudioLevelEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("audio.level"),
  trackId: z.string(),
  rms: z.number(),
  peak: z.number(),
  dbfs: z.number(),
});

export const SpeechPartialEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("speech.partial"),
  trackId: z.string(),
  text: z.string(),
});

export const SpeechDeltaEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("speech.delta"),
  trackId: z.string(),
  text: z.string(),
  replaces: z.string().optional(),
});

export const SpeechFinalEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("speech.final"),
  trackId: z.string(),
  text: z.string(),
  confidence: z.number().optional(),
});

export const SpeechPauseEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("speech.pause"),
  trackId: z.string(),
  pendingText: z.string(),
  silenceMs: z.number(),
});

export const AgentSubmitEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("agent.submit"),
  requestId: z.string(),
  text: z.string(),
});

export const AgentDeltaEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("agent.delta"),
  requestId: z.string(),
  delta: z.string(),
  seq: z.number(),
});

export const AgentCompleteEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("agent.complete"),
  requestId: z.string(),
  text: z.string(),
  tokenUsage: z.object({ input: z.number(), output: z.number() }).optional(),
});

export const AgentThinkingEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("agent.thinking"),
  requestId: z.string(),
});

export const AgentToolStartEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("agent.tool_start"),
  requestId: z.string(),
  toolCallId: z.string(),
  title: z.string().optional(),
});

export const AgentToolDoneEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("agent.tool_done"),
  requestId: z.string(),
  toolCallId: z.string(),
  status: z.string(),
});

export const AgentHistoryEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("agent.history"),
  role: z.string(),
  text: z.string(),
  requestId: z.string().optional(),
  toolCallId: z.string().optional(),
});

export const ControlInterruptEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("control.interrupt"),
  reason: z.string(),
});

export const ControlStateEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("control.state"),
  component: z.string(),
  state: z.string(),
});

export const ControlErrorEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("control.error"),
  component: z.string(),
  message: z.string(),
  fatal: z.boolean(),
});

export const LifecycleReadyEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("lifecycle.ready"),
  component: z.string(),
});

export const LifecycleDoneEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("lifecycle.done"),
  component: z.string(),
});

export const LogEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("log"),
  level: z.enum(["info", "warn", "error", "debug"]),
  component: z.string(),
  message: z.string(),
});

export const PlayerStatusEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("player.status"),
  playing: z.unknown(),
  agentState: z.unknown(),
  sfxActive: z.boolean(),
});

export const NodeStatusEventSchema = OrchestratorStampSchema.extend({
  type: z.literal("node.status"),
  text: z.string(),
});

export const PipelineEventSchema = z.discriminatedUnion("type", [
  AudioChunkEventSchema,
  AudioLevelEventSchema,
  SpeechPartialEventSchema,
  SpeechDeltaEventSchema,
  SpeechFinalEventSchema,
  SpeechPauseEventSchema,
  AgentSubmitEventSchema,
  AgentDeltaEventSchema,
  AgentCompleteEventSchema,
  AgentThinkingEventSchema,
  AgentToolStartEventSchema,
  AgentToolDoneEventSchema,
  AgentHistoryEventSchema,
  ControlInterruptEventSchema,
  ControlStateEventSchema,
  ControlErrorEventSchema,
  LifecycleReadyEventSchema,
  LifecycleDoneEventSchema,
  LogEventSchema,
  PlayerStatusEventSchema,
  NodeStatusEventSchema,
]);
