/**
 * AUTO-GENERATED by acpfx-codegen from packages/schema (Rust).
 * DO NOT EDIT — re-run `cargo run -p acpfx-schema --bin acpfx-codegen`.
 */

import { z } from "zod";

// ---- Manifest Types ----

export type ArgumentType = "string" | "number" | "boolean";

export interface ManifestArgument {
  type: ArgumentType;
  default?: unknown;
  description?: string;
  required?: boolean;
  enum?: unknown[];
}

export interface ManifestEnvField {
  required?: boolean;
  description?: string;
}

export interface NodeManifest {
  name: string;
  description?: string;
  consumes: string[];
  emits: string[];
  arguments?: Record<string, ManifestArgument>;
  additional_arguments?: boolean;
  env?: Record<string, ManifestEnvField>;
}

// ---- Manifest Zod Schemas ----

export const ArgumentTypeSchema = z.enum(["string", "number", "boolean"]);

export const ManifestArgumentSchema = z.object({
  type: ArgumentTypeSchema,
  default: z.unknown().optional(),
  description: z.string().optional(),
  required: z.boolean().optional(),
  enum: z.array(z.unknown()).optional(),
});

export const ManifestEnvFieldSchema = z.object({
  required: z.boolean().optional(),
  description: z.string().optional(),
});

export const NodeManifestSchema = z.object({
  name: z.string(),
  description: z.string().optional(),
  consumes: z.array(z.string()),
  emits: z.array(z.string()),
  arguments: z.record(z.string(), ManifestArgumentSchema).optional(),
  additional_arguments: z.boolean().optional(),
  env: z.record(z.string(), ManifestEnvFieldSchema).optional(),
});
