//! Build script: embed npm package versions into the orchestrator binary.
//!
//! Reads all packages/*/package.json, extracts @acpfx/* names and versions,
//! and generates a const lookup table so npx uses pinned versions instead of @latest.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let packages_dir = Path::new(&manifest_dir).parent().unwrap();

    let mut entries = Vec::new();

    if let Ok(dirs) = fs::read_dir(packages_dir) {
        for entry in dirs.flatten() {
            let pkg_json_path = entry.path().join("package.json");
            if !pkg_json_path.exists() {
                continue;
            }

            // Tell Cargo to re-run if any package.json changes
            println!(
                "cargo:rerun-if-changed={}",
                pkg_json_path.display()
            );

            let content = match fs::read_to_string(&pkg_json_path) {
                Ok(c) => c,
                Err(_) => continue,
            };

            // Minimal JSON parsing — extract "name" and "version" fields
            let parsed: serde_json::Value = match serde_json::from_str(&content) {
                Ok(v) => v,
                Err(_) => continue,
            };

            let name = match parsed.get("name").and_then(|v| v.as_str()) {
                Some(n) if n.starts_with("@acpfx/") => n,
                _ => continue,
            };

            let version = match parsed.get("version").and_then(|v| v.as_str()) {
                Some(v) => v,
                None => continue,
            };

            entries.push((name.to_string(), version.to_string()));
        }
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::from("// Generated by build.rs — do not edit\n");
    code.push_str("pub const PKG_VERSIONS: &[(&str, &str)] = &[\n");
    for (name, version) in &entries {
        code.push_str(&format!("    (\"{name}\", \"{version}\"),\n"));
    }
    code.push_str("];\n");

    let dest = Path::new(&out_dir).join("pkg_versions.rs");
    fs::write(dest, code).unwrap();
}
